RECORD_SIZE = 50
START_MARKER = 0x7E
END_MARKER = 0x7F

# Firmware rolling status schedule. One status appears in every downlink
# packet, advancing by one slot per packet.
STATUS_SCHEDULE = [
    0x21, 0x22, 0x23, 0x24, 0x25, 0x28, 0x2B, 0x2E,
    0x31, 0x32, 0x33, 0x34, 0x35, 0x36,
    0x3D, 0x3E, 0x3F, 0x40,
    0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48,
    0x49, 0x4A, 0x4B, 0x4C,
    0x4D, 0x4E, 0x4F,
    0x50, 0x51, 0x52,
    0x53, 0x54, 0x55,
]

STATUS_TYPE_NAMES = {
    0x21: "System Uptime",
    0x22: "Main Loop Count",
    0x23: "Worst Loop Time",
    0x24: "CPU Frequency",
    0x25: "Telemetry Core Temperature",
    0x28: "Telemetry Last Reset Cause",
    0x2B: "Telemetry Last Error",
    0x2E: "Telemetry Degraded Modules",
    0x31: "SD Records Written",
    0x32: "SD Write Failures",
    0x33: "SD Free Space",
    0x34: "Session File Index",
    0x35: "Ring Buffer Depth",
    0x36: "Ring Buffer Overflows",
    0x3D: "SiPM Thresholds 1-4",
    0x3E: "SiPM Thresholds 5-8",
    0x3F: "SiPM Thresholds 9-12",
    0x40: "SiPM Thresholds 13-16",
    0x41: "SiPM Average ADC 1-2",
    0x42: "SiPM Average ADC 3-4",
    0x43: "SiPM Average ADC 5-6",
    0x44: "SiPM Average ADC 7-8",
    0x45: "SiPM Average ADC 9-10",
    0x46: "SiPM Average ADC 11-12",
    0x47: "SiPM Average ADC 13-14",
    0x48: "SiPM Average ADC 15-16",
    0x49: "IMU Heading/Pitch",
    0x4A: "IMU Roll/Calibration",
    0x4B: "IMU Acceleration XY",
    0x4C: "IMU Acceleration Z",
    0x4D: "Temperature Top/Middle",
    0x4E: "Temperature Middle/Bottom",
    0x4F: "Temperature GPS/Mag/Computation",
    0x50: "Heater Duties",
    0x51: "Fan Duties",
    0x52: "Pressure Full Resolution",
    0x53: "Uplink Commands Accepted",
    0x54: "Uplink Commands Rejected",
    0x55: "Downlink Record Count",
}

TELEMETRY_MODULE_NAMES = {
    1: "main",
    2: "acquisition_handler",
    3: "secondary_trigger_handler",
    4: "sensor_handler",
    5: "bmp280_temperature_array",
    6: "bno055_imu_magnetometer",
    7: "gps_receiver",
    8: "data_recorder",
    9: "sd_writer",
    10: "health_checker",
    11: "removed_cpu_temperature_controller",
    12: "communication_module",
    13: "downlink_module",
    14: "uplink_module",
    15: "temperature_controller",
    16: "heater_controller",
    17: "fan_controller",
    18: "sipm_status_receiver",
}

CSV_HEADER = [
    "packet_number",
    "sequence_number",
    "payload_id",
    "timestamp_unix",
    "timestamp_utc",
    *[f"sipm_{idx:02d}_trigger_count" for idx in range(1, 17)],
    "threshold_01_mv",
    "threshold_02_mv",
    "threshold_03_mv",
    "threshold_04_mv",
    "pressure_mbar",
    "satellite_index",
    "satellite_count_range",
    "altitude_m",
    "magnetometer_x_uT",
    "magnetometer_y_uT",
    "magnetometer_z_uT",
    "sipm_stack_temp_c",
    "power_board_temp_c",
    "control_board_temp_c",
    "sipm_teensy1_temp_c",
    "sipm_teensy2_temp_c",
    "telemetry_teensy_temp_c",
    "telemetry_board_temp_c",
    "status_type",
    "status_type_hex",
    "status_name",
    "status_data",
    "status_data_signed",
    "status_data_hex",
    "status_decoded",
    "status_roll_index",
    "status_expected_type",
    "status_expected_type_hex",
    "status_schedule_ok",
    "crc_received",
    "crc_calculated",
    "crc_ok",
    "frame_ok",
    "raw_hex",
]
